# Generated by Django 5.2 on 2025-04-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_reccuringentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_expense',
        ),
    ]
